include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_import: error
    unused_local_variable: error
    unused_field: error
    unused_element: error
    dead_code: error
    avoid_print: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_declarations: error

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - require_trailing_commas
    - sort_child_properties_last
    - use_super_parameters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - avoid_redundant_argument_values
